on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Install dependencies
        run: |
          npm install
      
      - name: Run linting
        run: |
          npm run lint
        continue-on-error: true

      - name: Run tests with coverage
        run: |
          npm test -- --forceExit -- --coverage
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Sdiabate1337_secure-cicd-demo
            -Dsonar.organization=Sdiabate1337
            -Dsonar.projectVersion=${{ github.sha }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.testExecutionReportPaths=coverage/test-report.xml

      - name: OWASP Dependency-Check
        uses: dependency-check/dependency-check-action@v2
        with:
          fail_on_high: true
          fail_on_medium: false
          fail_on_low: false
          format: 'HTML'
          out: 'report'
          args: >
            --enableExperimental
            --failOnCVSS 7
            --suppression suppression.xml
    
      - name: Archive dependency check results
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
          retention-days: 5

      - name: Build Docker image
        run: |
          docker build -t secure-cicd-app:${{ github.sha }} .
    
      - name: Basic vulnerability scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-cicd-app:${{ github.sha }}
          format: 'table'
          exit-code: 0  # Not failing the build for educational purposes
          severity: 'HIGH,CRITICAL'

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            junit-*.xml
            test-*.json
          retention-days: 5