on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Install dependencies
        run: |
          npm install
      
      - name: Run linting
        run: |
          npm run lint
        continue-on-error: true

      - name: Run tests with coverage
        run: |
          npm test -- --forceExit --coverage ./app.test.js --coverageReporters=lcov --coverageReporters=text
        continue-on-error: true
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sdiabate1337_secure-cicd-pipeline-demo
            -Dsonar.organization=Sdiabate
            -Dsonar.projectVersion=${{ github.sha }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'secure-cicd-demo'
          path: '.'
          format: 'HTML'
          out: 'report'
          args: >
            --enableExperimental
            --failOnCVSS 7
            --suppression suppression.xml
    
      - name: Archive dependency check results
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: report
          retention-days: 5

      - name: Build Docker image
        run: |
          docker build -t secure-cicd-app:${{ github.sha }} .
    
      - name: Basic vulnerability scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-cicd-app:${{ github.sha }}
          format: 'table'
          exit-code: 0  # Not failing the build for educational purposes
          severity: 'HIGH,CRITICAL'

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            junit-*.xml
            test-*.json
          retention-days: 5